version: '3.8'

services:
  msvoo-db:
    image: postgres:15
    container_name: msvoo-db
    environment:
      POSTGRES_DB: msvoo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '@123Mudar'
    ports:
      - "5436:5432"
    networks:
      - ms-network
    volumes:
      - msvoo-db-data:/var/lib/postgresql/data

  voo:
    build:
      context: .
    container_name: msvoo
    depends_on:
      - msvoo-db
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_DATASOURCE_URL: jdbc:postgresql://msvoo-db:5432/msvoo
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: '@123Mudar'
    ports:
      - "9091:9091"
    networks:
      - ms-network

networks:
  ms-network:
    external: true

volumes:
  msvoo-db-data:
