spring:
  application:
    name: autenticacao-service
  rabbitmq:
    host: rabbitmq
    username: guest
    password: guest
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      host: mongodb
      port: 27017
  mail:
    host: smtp.gmail.com
    port: 587
    username: emiratadsairlines.noreply@gmail.com
    password: ${EMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true
            required: true
          ssl:
            trust: smtp.gmail.com
gateway:
  url: ${GATEWAY_URL:http://localhost:3030}
api:
  security:
    token:
      secret: ${SECRET_API_KEY}