version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # Porta para comunicação interna (RabbitMQ)
      - "15672:15672"  # Porta para painel web
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - ms-network

networks:
  ms-network:
    external: true
