spring:
  datasource:
    url: jdbc:postgresql://${SPRING_DATASOURCE_HOST:msfuncionario-db}:${SPRING_DATASOURCE_PORT:5432}/${SPRING_DATASOURCE_DATABASE:funcionario_db}
    username: ${SPRING_DATASOURCE_USERNAME:funcionario_user}
    password: ${SPRING_DATASOURCE_PASSWORD:funcionario_pass}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: msfuncionario
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

server:
  port: 9090
