version: '3.8'

services:
  msfuncionario-db:
    image: postgres:15
    container_name: msfuncionario-db
    environment:
      POSTGRES_DB: msfuncionario
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '@123Mudar'
    ports:
      - "5432:5432"
    networks:
      - ms-network
    volumes:
      - msfuncionario-db-data:/var/lib/postgresql/data
      
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"      
      - "15672:15672"   
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - ms-network

  msfuncionario:
    build: .
    container_name: msfuncionario
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://msfuncionario-db:5432/msfuncionario
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: '@123Mudar'
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    depends_on:
      - msfuncionario-db
    networks:
      - ms-network

volumes:
  msfuncionario-db-data:

networks:
  ms-network:
