version: "3.8"

services:
  msfuncionario-db:
    image: postgres:15
    container_name: msfuncionario-db
    environment:
      POSTGRES_DB: funcionario_db
      POSTGRES_USER: funcionario_user
      POSTGRES_PASSWORD: funcionario_pass
    ports:
      - "5435:5432"
    volumes:
      - funcionario-db-data:/var/lib/postgresql/data
    networks:
      - ms-network

  msfuncionario:
    build: .
    container_name: msfuncionario
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://msfuncionario-db:5432/funcionario_db
      SPRING_DATASOURCE_USERNAME: funcionario_user
      SPRING_DATASOURCE_PASSWORD: funcionario_pass
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    depends_on:
      - msfuncionario-db
    networks:
      - ms-network

volumes:
  funcionario-db-data:

networks:
  ms-network:
    external: true
