version: "3.8"

services:
  msreserva-db:
    image: postgres:15
    container_name: msreserva-db
    environment:
      POSTGRES_DB: reserva_db
      POSTGRES_USER: reserva_user
      POSTGRES_PASSWORD: reserva_pass
    ports:
      - "5434:5432"  # Mapeia 5434 no host para 5432 no container
    volumes:
      - reserva-db-data:/var/lib/postgresql/data
      # - ./db:/docker-entrypoint-initdb.d
    networks:
      - ms-network

  msreserva:
    build: .
    container_name: msreserva
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://msreserva-db:5432/reserva_db # Usa 5432 (porta padrão dentro da rede Docker)
      SPRING_DATASOURCE_USERNAME: reserva_user
      SPRING_DATASOURCE_PASSWORD: reserva_pass
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    depends_on:
      - msreserva-db
    networks:
      - ms-network

volumes:
  reserva-db-data:

networks:
  ms-network:
    external: true