spring:
  data:
    mongodb:
      uri: mongodb://mongo:27017/authdb

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

  mail:
    host: smtp.gmail.com
    port: 587
    username: guilherme.viol1914@gmail.com
    password: exxp djka zhab szxt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
    secret: segredo123
server:
  port: 8083